### ISSUE TITLE
Suggestion for Adding a Dropdown Menu to Select Channels in the Player

### ISSUE THREAD

**Issue by ghost** [jailsonsb2/RadioPlayer-ZenoRadio#2]
Dear Developer,
I would like to express my sincere gratitude for your excellent work and the player, which integrates perfectly with AzuraCast.

I have a small request:
Would it be possible to consider adding a dropdown menu to the player for selecting channels in the case of multi-channel radio stations? This could be quite useful for users who listen to different channels with varying music.

I would greatly appreciate your consideration of this idea. Thank you in advance for your response.

Best regards,
Andry.

**Comment by jailsonsb2** [comment]
I will consider including this in future versions.
